### ISSUE TITLE
Discussion: ExpandoObjectAdapter does not assume case insensitivity

### ISSUE THREAD

**Issue by jbagga** [aspnet/JsonPatch#103]
When applying a json patch to `ExpandoObject`s, case insensitive search will not be used to match the path segment to the object's dictionary keys. Instead, the path segment will be resolved using the `NamingStrategy` defined in the `IContractResolver`.

See announcement: https://github.com/aspnet/Announcements/issues/269

**Comment by rynowak** [comment]
FYI we've done this change to be consistent with how JSON.NET deals with casing and dictionaries. The **right way** to configure this is to use the naming strategy.

Some of the decisions in this repo were taken which MVC was still using the pascal case contract resolver and don't really make much sense anymore.

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2430
