### ISSUE TITLE
Patching of records (readonly entities) fails

### ISSUE THREAD

**Issue by MovGP0** [aspnet/JsonPatch#119]
The following code does not work on readonly entities: 
```csharp
patch.ApplyTo(readonlyentity);
```

It should be possible to do something like this: 

```csharp
var patchedentity = patch.ApplyTo(readonlyentity);
```

**Comment by MovGP0** [comment]
One way of doing this would be to convert the readonly entity to an `Newtonsoft.Json.Linq.JObject`, apply the patches, and deserialize to the original datatype.

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2426
