### ISSUE TITLE
What is the recommended way to integrate JsonPatchExceptions with ASP.NET Core?

### ISSUE THREAD

**Issue by snebjorn** [aspnet/JsonPatch#122]
If `patchDocument.ApplyTo(objectToUpdate);` throws In your controller what is the recommended way to handle that?

I was thinking something like

```
try 
{
    patchDocument.ApplyTo(objectToUpdate)
}
catch (JsonPatchException e)
{
    ModelState.AddModelError(e);
}
```

**Comment by rynowak** [comment]
There's an override of `ApplyTo` that takes modelstate: https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Formatters.Json/JsonPatchExtensions.cs

**Comment by snebjorn** [comment]
I totally missed that. Thank you!
