### ISSUE TITLE
Patch fails if StringEnumConverter is used

### ISSUE THREAD

**Issue by Morcatko** [aspnet/JsonPatch#123]
`JsonPatchDocument<T>.ApplyTo()` fails with `Microsoft.AspNetCore.JsonPatch.Exceptions.JsonPatchException: 'The value 'XXXX' is invalid for target location.'` in case the model has `[JsonConverter(typeof(StringEnumConverter))]` attribute and the client "replaces" this particular property

```
    public class DataModel
    {
        [JsonConverter(typeof(StringEnumConverter))]
        public UnitEnum Unit { get; set; }
    }

    public enum UnitEnum
    {
        [EnumMember(Value = "Meter")]
        m,
        [EnumMember(Value = "Foot")]
        ft,
    }
```

Following patch is properly parsed by InputFormatter, but will cause an exception when `ApplyTo()` is called
```
{ op = "replace", path = "/unit", value = "Foot" }
```

Reproduced on .NET Core 2.0 (Windows x64)
Test project to reproduce - [PatchBug.zip](https://github.com/aspnet/JsonPatch/files/1443418/PatchBug.zip)
I guess the same can happen with any other attribute controlling de/serialization

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2423
