### ISSUE TITLE
Paths containing '.' trigger JsonPatchException

### ISSUE THREAD

**Issue by arerlend** [aspnet/JsonPatch#124]
In [/src/Microsoft.AspNetCore.JsonPatch/Internal/PathHelpers.cs](https://github.com/aspnet/JsonPatch/blob/dev/src/Microsoft.AspNetCore.JsonPatch/Internal/PathHelpers.cs):

`if (path.Contains(".") || path.Contains("//") || path.Contains(" ") || path.Contains("\\"))
{
    throw new JsonPatchException(Resources.FormatInvalidValueForPath(path), null); 
}`

The spec at jsonpatch.com doesn't ever specify that '.' characters are invalid or must be escaped.

**Comment by Eilon** [comment]
Yeah this just looks like a plain old bug. The JSON PATCH RFC Section 4 (https://tools.ietf.org/html/rfc6902#section-4) points at https://tools.ietf.org/html/rfc6901 to define allowed JSON paths, and I don't see any reason to disallow the `.` character.

**Comment by Eilon** [comment]
@jbagga there's already a PR for this, so I'm assigning this bug to you to review & merge.

**Comment by arerlend** [comment]
That's a far better spec.  Didn't realize it existed... TIL

**Comment by rynowak** [comment]
Fixed by 70c8133 - thanks!
