### ISSUE TITLE
Nancy compliancy

### ISSUE THREAD

**Issue by jchannon** [aspnet/JsonPatch#17]
I just read the great article from @benfoster http://benfoster.io/blog/aspnet-core-json-patch-partial-api-updates and was curious if anyone has tried or would be willing to try to see if this would work with [Nancy](http://github.com/nancyfx/nancy)?

**Comment by jchannon** [comment]
**UPDATE** I've discovered that that MVC functionality comes from a MVC extension so hopefully we could do the same for Nancy https://github.com/aspnet/Mvc/blob/master/src/Microsoft.AspNet.Mvc.Formatters.Json/JsonPatchExtensions.cs

**Comment by Eilon** [comment]
Yeah the JsonPatch feature here is technically even completely independent of ASP.NET. If you notice, [this project](https://github.com/aspnet/JsonPatch/blob/dev/src/Microsoft.AspNetCore.JsonPatch/project.json) doesn't reference anything from ASP.NET, so it's just a plain old class library and can theoretically be used anywhere, as long as you have the right hook-up. So, ASP.NET Core MVC just happens to be the only place we hooked it up.

**Comment by jchannon** [comment]
I hooked it here if interested https://github.com/jchannon/nancy.jsonpatch

**Comment by jchannon** [comment]
Just realised there is this non core library
https://github.com/DSaunders/Nancy.JsonPatch/blob/master/README.md

**Comment by Eilon** [comment]
Nice!

**Comment by jchannon** [comment]
Now running on netcore RTM with sample https://twitter.com/jchannon/status/757236573578616832
