### ISSUE TITLE
Incompatible with netstandard1.5?

### ISSUE THREAD

**Issue by Daniel15** [aspnet/JsonPatch#23]
I'm trying to upgrade one of my libraries from ASP.NET 5 RC1 to ASP.NET Core RC2. I'm seeing the following error:

```
      Package Newtonsoft.Json 8.0.3 is not compatible with netstandard1.5 (.NETStandard,Version=v1.5). Package Newtonsoft.
  Json 8.0.3 supports:
        - net20 (.NETFramework,Version=v2.0)
        - net35 (.NETFramework,Version=v3.5)
        - net40 (.NETFramework,Version=v4.0)
        - net45 (.NETFramework,Version=v4.5)
        - portable-dnxcore50+net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=net45+wp80+win8+wpa81+dnxcore50)
        - portable-net40+sl5+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile328)
```

The `Newtonsoft.Json` dependency is coming from `Microsoft.AspNetCore.JsonPatch`, as a dependency of `Microsoft.AspNetCore.Mvc.Formatters.Json`.

**Comment by Daniel15** [comment]
Seems like I had to adjust the `frameworks` section in `project.json` as follows:
```
  "frameworks": {
    "netstandard1.5": {
      "imports": [
	    "dnxcore50"
	  ]
	}
  },
```

This is super confusing. Why do I need to do this?

**Comment by Eilon** [comment]
@Daniel15 yep, that is currently a known issue and will be fixed very soon. The latest released version of Json.NET doesn't yet support the new `netstandard` target framework monikers (TFMs), so you have to do these ugly imports (e.g. [this](https://github.com/aspnet/JsonPatch/blob/dev/test/Microsoft.AspNetCore.JsonPatch.Test/project.json#L24-L27). However, by the time ASP.NET Core RTMs there will be a final version of Json.NET that supports it (there's a pre-release version already), so these will go away.

The reason they are needed right now is that the new libraries all support `netstandard`, but some libraries don't, so for those libraries that don't support it, NuGet/.NET CLI don't know which `lib/**/*.dll` to load. So you have to tell it to "import" a TFM that you "promise" is compatible. In this case, `dnxcore50`, and certain `portable-*` TFMs are compatible, so it works. It's a way of telling the system, "Trust me, I know what I'm doing!"

**Comment by Daniel15** [comment]
>  but some libraries don't, so for those libraries that don't support it, NuGet/.NET CLI don't know which lib/**/*.dll to load

@Eilon Couldn't NuGet / .NET CLI have a built-in mapping of new TFM to old TFM, rather than making everyone do it manually in their `package.json`?

**Comment by Eilon** [comment]
@Daniel15 it does have many mappings built-in, but I think in this case there's an issue because there's no *actual* guarantee that the code is compatible based on the TFMs, but it just happens to be that it is compatible if you actually try it.
