### ISSUE TITLE
Honor JsonProperty when serializing a JsonPatchDocument.

### ISSUE THREAD

**Issue by KevinDockx** [aspnet/JsonPatch#29]
An issue was logged on the issue list of Marvin.JsonPatch (on which AspNetCore.JsonPatch is based, which is why I'm logging this issue) regarding honoring JSON.NET's JsonProperty (https://github.com/KevinDockx/JsonPatch/issues/44#issuecomment-225681404).  

The AspNetCore version supports this when applying a patchDoc to a class that has properties decorated with [JsonProperty] attributes. Marvin.JsonPatch doesn't (PCL stuff), so that's not an issue for AspNetCore's version.  But it's the last comment of Amnesia1187 that's of importance, as it affects AspNetCore.JsonPatch. 

It's regarding creating a JsonPatchDocument on the consumer-side of things. Such a document is serialized to a Json list of operations, and the "path"-portion contains the property name the patch operation affects.  That part apparently does not respect JsonProperty values. 

So, if you create a JsonPatchDocument<MyClass>, and MyClass contains a property "Name" decorated with JsonProperty("RealName"), it will be serialized to path: "/name" instead of "realName". 

I feel it should serialize to realName.  Thoughts on this?

**Comment by KevinDockx** [comment]
FYI, I fixed this issue in Marvin.JsonPatch.  I'd be happy to provide a PR with the required changes :)

**Comment by Eilon** [comment]
Looks like https://github.com/aspnet/JsonPatch/pull/35 was merged, so closing this bug. Thanks!
