### ISSUE TITLE
Support for using DTOs (with autoMapper)

### ISSUE THREAD

**Issue by arielcloud** [aspnet/JsonPatch#31]
I searched for solution to this use case, and saw [here](https://github.com/aspnet/Mvc/issues/1976) that @sergkr ask for this. any news about this? where can I read docs? thanks!

**Comment by Eilon** [comment]
We have no plans to implement this at this time. Putting on the backlog for now.

**Comment by arielcloud** [comment]
So, if I using DTO in my object (and map them to EF entities) I should look for another solution, or you have any work around to deal with this? thanks

**Comment by Eilon** [comment]
@arielcloud can you share more about what you're trying to do? The [AutoMapper NuGet package](https://www.nuget.org/packages/AutoMapper/) supports .NET Core so it should run fine within ASP.NET Core. But beyond that, it depends on the specific scenario you have (e.g. model binding, using Entity Framework Core, something else...).

**Comment by arielcloud** [comment]
I'm using EF core, I have web api project with crud operation. I want to be able to get from client changes for entities, and save them to the db. but in my controller I expose just DTOs, so I'm get exactly the problem I linked to above: 

"The above example wouldn't actually work since we're trying to apply a patch document of type DTO.Expense against an entity of type Entities.Expense. I think being able to support this use case is kind of important, as otherwise we're limiting being able to use Patch in all but the simplest of APIs."

In this link @sergkr describe the exact problem I'm having (starting in: "Second, it's common to have separate classes for domain objects ("entities") versus what you send/receive over the wire ("DTOs")".

thanks

**Comment by Eilon** [comment]
Hmm, looking at the code it *looks* like you could do this:

```c#
public IActionResult UpdateProduct(int id, JsonPatchDocument<ProductDto> productDto)
{
    Product existingProduct = db.GetProduct(id);
    productDto.ApplyTo(existingProduct);
}
```

Though I agree that using AutoMapper in this would be quite complex.

This is not an area we plan to make any significant changes in, but if you (or anyone) has a prototype or something we could look at, we can certainly reconsider.

**Comment by arielcloud** [comment]
Hi guess you mean 
` ProductDto existingProduct = db.GetProduct(id);`
otherwise
'productDto.ApplyTo(existingProduct);'
not compiled.

but then, if I want to verify the changes (for example - if I allow to change only part of
Account) - I should test it on the controller (and I want to avoid logic on controller), because business logic layer dont know DTOs.

eventually, I succeeded use it after I removed the type from JsonPatchDocument,
so that instead of 'JsonPatchDocument<ProductDto> patch' I use just 'JsonPatchDocument patch'.
then I can pass patch to BL layer, and apply it (also) to Account instance.

What do u think about my solution? thanks!

**Comment by arielcloud** [comment]
Now I saw that if I use JsonPatchDocument without entity type, I can't validate it against ModelState 

```
public AccountDTO Patch(int id, [FromBody]JsonPatchDocument patch)
        {
            var accountToTestValidation = new AccountDTO();
            patch.ApplyTo(accountToTestValidation, ModelState); //this wont compile if I dont pass `JsonPatchDocument <AccountDto> ` param

```

**Comment by Eilon** [comment]
@arielcloud yeah looking at the API it looks like there's a generic version of `ApplyTo` that you can't use (because it uses T for both sides), but also a non-generic version of `ApplyTo` that can take any two types and it matches based on property names, etc.

Did you get this working? What is the validation issue you were having?

**Comment by arielcloud** [comment]
Yeah, it is working.

the problem is that if I use it so, I cant use the `ApplyTo` version which take the `ModelState` param  and fill it with the validation errors the patch cause (if exists) to use later with 

```
if (!ModelState.IsValid)
            {
                throw new InvalidDataException(
```

but I still can manually check the patched object validation by 
```
patch.ApplyTo(patched);
TryValidateModel(patched);
```

**Comment by arielcloud** [comment]
Now I saw that I can do that simply by using `CreateMap(typeof(JsonPatchDocument<>), typeof(JsonPatchDocument<>));
            CreateMap(typeof(Operation<>), typeof(Operation<>));`
that's all!

**Comment by candoumbe** [comment]
@Eilon 
An other way to work this out could be able to convert an `Operation<TEntity>` to its equivalent `Action<TEntity>`. or to `Func<TEntity, TEntity`
so that after converting from JsonPatchDocument<DTO> to JsonPatchDocument<TEntity> as @arielcloud suggested, one can work with just a list of transformation to apply in a service.
In this way, only the controller layer would depends on the JsonPatchDocument whilst other layers won't

**Comment by Eilon** [comment]
Closing because there are no plans to implement this.

**Comment by sachinpachori** [comment]
This is a common scenario where your DTO/viewmodel could be different from the Entities. In this case how to use this JSONPatch with ApplyTo function.  If possible, I think you should work on providing this feature.

**Comment by rynowak** [comment]
**Hi, it looks like you are posting on a closed issue/PR/commit!**

We're very likely to lose track of your bug/feedback/question unless you:
1. Open a new issue
2. Explain very clearly what you need help with
3. If you think you have found a bug, include detailed repro steps so that we can investigate the problem

Thanks!
