### ISSUE TITLE
Patching of dictionaries should be case sensitive on keys

### ISSUE THREAD

**Issue by kichalla** [aspnet/JsonPatch#37]
The current code handles all (dynamic(example: ExpandoObject implements `IDictionary<string,object>`) or not) dictionaries which implement `IDictionary<string, object>` in a case Insensitive way. This is an incorrect behavior.

For example:
1. When Json.net deserializes data into a regular IDictionary<,> it considers the keys **case-sensitive**.
2. When Json.net deserializes data into a regular Poco type, it considers the property names **case-Insensitive.**

Considering the above behavior, we should do the following in json patch:
1. For dynamic types (like ExpandoObject, DynamicObject etc.), the matching of keys should be case-Insensitive. This is to keep the behavior consistent with a Poco type where the property names are considered **case-Insensitive.**
2. For dictionaries, keep the default json.net behavior, i.e. keep them **case sensitive.**

@dougbu @rynowak

**Comment by Eilon** [comment]
@kichalla can you link to the PR/commit where you previously fixed this and then close this? Thanks!

**Comment by kichalla** [comment]
81931e75d48370cf9163254523b1f6c4bcc92acb
