### ISSUE TITLE
Dictionary patching should also support non 'string' type keys

### ISSUE THREAD

**Issue by kichalla** [aspnet/JsonPatch#39]
@rynowak @dougbu

**Comment by Eilon** [comment]
The scenario is something like this:

The JSON structure:

```json
{
	"123": { "name": "Kiran", "age": 20 },
	"456": { "name": "Ryan", "age": 30 },
}
```

The model:

```c#
public class MyModel
{
    public Dictionary<int, Customer> Customers { get; set; }
}
```

And the idea is that the stringified integers should be parsed as integers so that the dictionary keys could be located.

**Comment by SkiGeek82** [comment]
I'm pretty sure I am having the same issue with Guids:

The JSON Structure:
`{
    "contacts": {
        "c2727f99-6669-4844-b30c-4fa1c0806d2d": {
            "id": "c2727f99-6669-4844-b30c-4fa1c0806d2d",
            "firstName": "Ben",
            "lastName": "Foster",
            "age": 30
        },
        "d705a11f-726f-498f-a625-b09343c731f9": {
            "id": "d705a11f-726f-498f-a625-b09343c731f9",
            "firstName": "Jen",
            "lastName": "Foster",
            "age": 25
        }
    }
}`

The Model:
`
    public class Contact
    {
        public Guid ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int Age { get; set; }

        public List<string> Links { get; set; }
    }    

public class ContactList
    {
        public IDictionary<Guid, Contact> Contacts { get; } = new Dictionary<Guid, Contact>();
    }`

**Comment by Eilon** [comment]
Yup, looks like the same issue.

**Comment by jbagga** [comment]
This is now supported as part of this PR 0f51c56. The key is converted to the type specified [here](https://github.com/aspnet/JsonPatch/blob/dev/src/Microsoft.AspNetCore.JsonPatch/Internal/DictionaryAdapterOfTU.cs#L23).

There are also some tests for it https://github.com/aspnet/JsonPatch/blob/dev/test/Microsoft.AspNetCore.JsonPatch.Test/DictionaryAdapterTest.cs#L34.

cc @Eilon

**Comment by Eilon** [comment]
@jbagga ah ok should we close this as a dup then?
