### ISSUE TITLE
Short circuit on the first operation failure when multiple operations are part of the json patch request

### ISSUE THREAD

**Issue by kichalla** [aspnet/JsonPatch#43]
This is a regression that I introduced with my check-in. I found this with a test in Entropy (I didn't knew there were tests for it in Entropy actually). 

Once this fixed, revert the following commit in Entropy:
https://github.com/aspnet/Entropy/commit/292a5c04cc59219d6e7ddeae729e4d8962611f6d

@rynowak @Eilon 

For reference: Snippet from Json Patch spec:

```
Evaluation of a JSON Patch document begins against a target JSON
   document.  Operations are applied sequentially in the order they
   appear in the array.  Each operation in the sequence is applied to
   the target document; the resulting document becomes the target of the
   next operation.  Evaluation continues until all operations are
   successfully applied or until an error condition is encountered.
```

**Comment by kichalla** [comment]
Hmm, so looks like this was not a regression after all. I verified this by a test to the branch state where it did not have my changes and noticed the tests fail.

**Comment by Eilon** [comment]
@kichalla please close.

**Comment by kichalla** [comment]
I was mistaken when i filed this issue and we already do short circuit on the first operation failure.
