### ISSUE TITLE
Missing support for JSON Pointer Escaping

### ISSUE THREAD

**Issue by sandorfr** [aspnet/JsonPatch#44]
The following JSON is valid:

``` json
{
  "foo/bar~" : "a value"
}
```

But currently the library does not support `~` and `/` as stated under [JSON Pointer section](http://jsonpatch.com/), so this can't be patched.

I'll open a pull request with a fix proposal.

**Comment by Eilon** [comment]
@kichalla do you have time to review the PR for this today? I'd like to get this into 1.1.0.

**Comment by kichalla** [comment]
@Eilon Sorry I actually didn't see the notification about this until few minutes back. Taking a look now.

**Comment by Eilon** [comment]
Looks like you merged this, so closing. Thanks!
