### ISSUE TITLE
JsonPatch - ModelState is invalid

### ISSUE THREAD

**Issue by MittiMartin** [aspnet/JsonPatch#47]
Hi,
I have a problem with jsonpatch in an asp.net core webapi project.
One of the controller:
```
    [HttpPatch("{id}")]
    public IActionResult Patch(int id, [FromBody]JsonPatchDocument<ContactPerson> contactPersonPatchDocument)
    {
        if (contactPersonPatchDocument == null)
        {
              return BadRequest();
        }

        var existingContactPerson = _context.ContactPersons.SingleOrDefault(x => x.Id == id);
        if (existingContactPerson == null)
        {
            return NotFound();
        }

        contactPersonPatchDocument.ApplyTo(existingContactPerson, ModelState);
        _context.SaveChanges();
        return Ok();
    }
```
`
I have the id because I want to update an specific entity. Is this right?

I'm using swagger for the http request. Here's my patch request:
![image](https://cloud.githubusercontent.com/assets/15977182/20015638/799468ce-a2bc-11e6-8775-09fb7a0b8fa6.png)

When I run this request I get the following response in swagger:
![image](https://cloud.githubusercontent.com/assets/15977182/20015783/1c189c00-a2bd-11e6-850b-00fe5a5af8a9.png)

And Visual Studio writes this output:
```
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request starting HTTP/1.1 PATCH http://localhost:5000/api/ContactPersons/1 application/json 75
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker:Information: Executing action method WebAPI.Controllers.ContactPersonsController.Patch (WebAPI) with arguments (1, ) - ModelState is Invalid
Microsoft.AspNetCore.Mvc.StatusCodeResult:Information: Executing HttpStatusCodeResult, setting HTTP status code 400
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker:Information: Executed action WebAPI.Controllers.ContactPersonsController.Patch (WebAPI) in 9.9579ms
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request finished in 26.4883ms 400
```

For information:

- The other operations like post, get,... are working well.
- I don't use DTOs, are they necessary?

What I'm doing wrong? Thanks.

**Comment by candoumbe** [comment]
@MittiMartin 
From what i can see, the body doesn't match the shape of the requested body model, as you're sending the json representation of an `Operation`
```
{
    "value": {},
    "path": "string",
    "op": "string",
    "from": "string"
  }
```
 instead of the json representations of the `JsonPatchDocument `(as stated in the capture you've submitted.
Even after correcting this issue, it won't work.
As a workaround, I've changed the parameter of the action from 
`Patch(int id, [FromBody] JsonPatchDocument<TModel> changes)` to
`Patch(int id, [FromBody] IEnumerable<Operation<TModel>> changes)` allowing me to successfully send PATCH requests to the endpoint.

Hope this help
Hopes this will help

**Comment by Eilon** [comment]
@kichalla can you investigate?

**Comment by kichalla** [comment]
@MittiMartin @candoumbe 

If you following the JsonPatch spec, the format of a jsonpatch document looks like below:
```
PATCH /my/data HTTP/1.1
   Host: example.org
   Content-Length: 326
   Content-Type: application/json-patch+json
   If-Match: "abc123"

   [
     { "op": "test", "path": "/a/b/c", "value": "foo" },
     { "op": "remove", "path": "/a/b/c" },
     { "op": "add", "path": "/a/b/c", "value": [ "foo", "bar" ] },
     { "op": "replace", "path": "/a/b/c", "value": 42 },
     { "op": "move", "from": "/a/b/c", "path": "/a/b/d" },
     { "op": "copy", "from": "/a/b/d", "path": "/a/b/e" }
   ]
```
As you can see the body is a json array with list of operations, so can you try again and let us know if it still doesn't work?
BTW we are fixing ApiExplorer in MVC to enable Swagger to describe the JsonPatchDocument contracts properly: https://github.com/aspnet/Mvc/issues/5464

**Comment by MittiMartin** [comment]
Yeah, thanks. I've used the false format of the JsonPatch.
Now it works. Thanks a lot.

**Comment by kichalla** [comment]
Thanks for verifying.
