### ISSUE TITLE
Consider update version of Newtonsoft.Json

### ISSUE THREAD

**Issue by MikhailNazarov** [aspnet/JsonPatch#5]
This project uses "Newtonsoft.Json": "6.0.6" therefore we have conflicts with other our assemblies because they use latest version 7.0.1. Old version of project used 7.0.1 version too (at least beta5)

**Comment by Eilon** [comment]
The projects generally have the lowest *allowed* dependency. You can always upgrade the version of Json.NET that you're using by specifying the reference in your project's `project.json` file. We want to allow version 6.0.6 and newer, which includes 7.x.
