### ISSUE TITLE
Honoring Microsoft.AspNet.Mvc.BindAttribute

### ISSUE THREAD

**Issue by AymanGaafar** [aspnet/JsonPatch#7]
Can this component honor the BindAttribute ?

i.e. If the class type that is being patched has an MVC BindAttribute and does not include certain property(ex: Prop1), then if Prop1 was found in the operations passed from the client, it will just be ignored.

**Comment by Eilon** [comment]
No plans to support it at this time.

**Comment by Eilon** [comment]
Though, it would unlikely ever support MVC's BindAttribute due to layering because JsonPatch can't depend on MVC. But perhaps some other attribute.

Though, can you just use Json.NET's attributes instead? It has a wide variety of features for controlling the serialization/deserialization of types.

**Comment by AymanGaafar** [comment]
I imagined the layering problem would cause this not to be implemented, but I think the Json attributes would work just like the BindAttributes, though I would highly recommend put this in the documentation if any.
