### ISSUE TITLE
Update Microsoft.AspNet.JsonPatch nuget package version

### ISSUE THREAD

**Issue by en-alepopa** [aspnet/JsonPatch#77]
Hi everyone,

The ASP NET Core version of this package is at version 1.1.1: https://www.nuget.org/packages/Microsoft.AspNetCore.JsonPatch/

But the ASP NET standard version of this package was not updated since 2015, at version 1.0.0-beta8: https://www.nuget.org/packages/Microsoft.AspNet.JsonPatch/1.0.0-beta8

I realise this may not be the proper platform to request this, but can you push to latest stable version for Microsoft.AspNet.JsonPatch on NuGet to 1.1.1 as well?

**Comment by rynowak** [comment]
The `Microsoft.AspNet.JsonPatch` package is just the old name of this package. You can use `Microsoft.AspNetCore.JsonPatch` on desktop framework (net451)

**Comment by en-alepopa** [comment]
Thanks! Can you guys update the https://www.nuget.org/packages/Microsoft.AspNet.JsonPatch/1.0.0-beta8 page with this information? At first sight, it's not clear that AspNetCore.JsonPatch can be used with AspNet 4.6

**Comment by Eilon** [comment]
The only thing we can do is un-list the package, which will probably solve this problem for most people. It won't show up in search results, etc.

**Comment by dennisroche** [comment]
Vote to close as package as been unlisted

**Comment by Eilon** [comment]
That specific version is unlisted, but I believe there are other versions that are still listed, such as https://www.nuget.org/packages/Microsoft.AspNet.JsonPatch/1.0.0-beta7.

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2433
