### ISSUE TITLE
Add builtin JObjectAdapter that implements IAdapter

### ISSUE THREAD

**Issue by maximpashuk** [aspnet/JsonPatch#84]
As for now builtin implementations for ```IAdapter``` are

**DictionaryAdapter**
**ExpandoObjectAdapter**
**ListAdapter**
**PocoAdapter**

In my case is useful to have ```JsonPatchDocument<JObject>``` and apply it to ```JObject``` from Newtonsoft.Json.

I use workaround
```csharp
var expandoObject = new ExpandoObject();
patchDoc.ApplyTo(expandoObject);
var jObject = JObject.FromObject(expandoObject);
```

However, it would be nice to have builtin ```IAdapter``` for ```JObject``` so I can call 
```
var jObject = new JObject();
patchDoc.ApplyTo(jObject)
```
 without any errors.

**Comment by maximpashuk** [comment]
Also I found that issue #75 can be fixed if support for JObject will be added.

```
patch.ApplyTo(JObject.Parse("{"region": "amer", "foo1": {"foo11": "val1", "foo12": 2}}"));
```

**Comment by Eilon** [comment]
Looks like this would be covered by https://github.com/aspnet/JsonPatch/issues/38.
