### ISSUE TITLE
Extension point

### ISSUE THREAD

**Issue by dario-hd** [aspnet/JsonPatch#88]
As far as I can see the extension point is the `ObjectAdapter`. So, basically the idea is to create a wrapper around it which implements the same interface. But `ObjectAdapter` is not injectable because of the `Action<JsonPatchError>` constructor parameter. 

In addition, I saw that [here](https://github.com/aspnet/JsonPatch/blob/dev/src/Microsoft.AspNetCore.JsonPatch/JsonPatchDocument.cs#L159) and [here](https://github.com/aspnet/JsonPatch/blob/dev/src/Microsoft.AspNetCore.JsonPatch/JsonPatchDocumentOfT.cs#L639) it is explicitly set to null.

Does it make sense to make it optional in order to allow it to be injectable?

That's what I did when I used this version https://github.com/KevinDockx/JsonPatch, but the parameterless constructor is not available anymore.

    public interface IPatchAdapter : IObjectAdapter
    {
    }

    public class PatchAdapter : IPatchAdapter
    {
        private readonly IObjectAdapter _objectAdapter;

        public PatchAdapter(IObjectAdapter objectAdapter)
        {
            _objectAdapter = Check.NotNull(objectAdapter, nameof(objectAdapter));
        }

        public void Add(Operation operation, object objectToApplyTo)
        {
            // ...
        }

        public void Copy(Operation operation, object objectToApplyTo)
        {
            // ...
        }

        public void Move(Operation operation, object objectToApplyTo)
        {
            // ...
        }

        public void Remove(Operation operation, object objectToApplyTo)
        {
            // ...
        }

        public void Replace(Operation operation, object objectToApplyTo)
        {
            // ...
        }
    }

**Comment by Eilon** [comment]
@dario-hd can you provide more info on the scenario you are trying to accomplish?

**Comment by dario-hd** [comment]
@Eilon the idea is to enhance the original `ObjectAdapter` implementation. In the end I managed to do it by registering `IObjectAdapter` as follow in Autofac:

    builder.Register(c => new ObjectAdapter(new DefaultContractResolver(), logErrorAction: null))
           .As<IObjectAdapter>();

I would create a constructor without `logErrorAction` in order to make it "more injectable".

**Comment by Eilon** [comment]
@dario-hd thanks for the extra info, we will evaluate this in our next team bug discussion.

**Comment by Eilon** [comment]
@dario-hd we took a quick look at this and we think we still need a bit more info. Can you provide info on what it is you're trying to inject? Maybe show the code that you'd like to be able to write when setting up your container and services?

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2431
