### ISSUE TITLE
Performing Test Operation with Operation<T> on a JsonPatchDocument<T> does not throw

### ISSUE THREAD

**Issue by patrick-hampton-avalara** [aspnet/JsonPatch#94]
The implementation of Operation<T> differs from Operation in that Operation<T> throws a JsonPatchException when Test is used.  This type of exception is caught and "reported", then the ApplyTo is short circuited  but the method returns.  In this scenario the caller has no way of knowing that anything failed.  
Recommend changing the exception type thrown by Operation<T>.ApplyTo to be consistent with Operation.  Alternatively (or in addition to) the catch in JsonPatchDocument should rethrow the exception that it caught so the caller is always aware of any exception that occurred.

**Comment by Eilon** [comment]
If we implement the `test` operation per https://github.com/aspnet/JsonPatch/issues/1, this issue would go away.

**Comment by jbagga** [comment]
`Test` operation is now supported as part of #1. Please feel free to reopen this if you run into a problem.
