### ISSUE TITLE
// root path for List<> type

### ISSUE THREAD

**Issue by rosspi** [aspnet/JsonPatch#98]
I am getting a path string to be generated from an expression to the root object that looks like this:
//
That is, x => x is turning into '//' when it should just be '/'.
This is just the case when the generic type of the document is a list.

When applying the apply function(s) it seems to be happy with the double slash, but I don't think this should be the case.

**Comment by Eilon** [comment]
@jbagga can you take a look and see what's going on here?

**Comment by jbagga** [comment]
@rosspi Can you share a sample/code snippet, and elaborate on how the actual and expected output differ? I can then investigate.

**Comment by rosspi** [comment]
It happens when the generic type is a list, and you're adding an item to the object itself (when using an expression like this: x => x).
If however, the expression points at something deeper than the object itself, then the resultant json path is ok.

```
class MyClass
{
        
}
class Program
{
    static void Main(string[] args)
    {
        var blah = new JsonPatchDocument<List<MyClass>>();
        blah.Add(x => x, new MyClass()); 

        Console.WriteLine(blah.Operations[0].path);
    }
}
```
